# Job definition block
shared:
  image: fedora:latest
jobs:
  main:
    requires: [~pr, ~commit]
    # Steps definition block.
    steps:
      - export: export GREETING="Hello, world!"
      - hello: echo $GREETING
      - set-metadata: meta set example.coverage 99.95
      - install_find: dnf install find # otherwise build cleanup fails
  second_job:
    requires: [main] # second_job will run after main job is done
    steps:
      - make_target: echo make greetings
      - get-metadata: meta get example
      - run_arbitrary_script: ./my_script.sh
